### ISSUE TITLE
Eval in REPL, "The handle is invalid"

### ISSUE THREAD

**Issue by palpha** [wuub/SublimeREPL#271]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "---\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\text_transfer.py", line 123, in run
    for rv in manager.find_repl(external_id):
  File "---\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 437, in find_repl
    if not (rv.repl and rv.repl.is_alive()):
  File "---\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repls\subprocess_repl.py", line 185, in is_alive
    return self.popen.poll() is None
  File "X/subprocess.py", line 916, in poll
  File "X/subprocess.py", line 1131, in _internal_poll
OSError: [WinError 6] The handle is invalid
```

I got it working by changing the `.poll()` call to a simple `self.popen != None`, but that's almost certainly the wrong approach ([commit](https://github.com/palpha/SublimeREPL/commit/9d0964200f51c80f524299d71e77e5ec4207e7c9)).

**Comment by stianlagstad** [comment]
I had this problem using R, and it turns out my problem was due to me opening sublime text from the command line. This solution from stackoverflow solved the problem for me: http://stackoverflow.com/questions/10438508/error6-while-trying-to-use-sublime-text-to-msbuild

**Comment by stianlagstad** [comment]
That was premature. It solved the problem for the first thing I send to the REPL, but the error comes for each command I use after that.

Excuse my ignorance, but where are you editing is_alive?

**Comment by zmLGBBM** [comment]
@wuub 

Same problem ([WinError 6] The handle is invalid) on **Windows 10 64bit** with **Sublime 3** and **Python 3.5** installed.
This work-around:

    def is_alive(self):
        return True

did the trick (though not perfect).

Hopefully this could be fixed soon. ;) Thanks for the package btw.

**Comment by 5j9** [comment]
Win 10. Python 3.5.

Steps to reproduce:

1. Open a python script.
2. Run a repl. (`ctrl+shift+p`, type `sublimerepl: python`, press `enter` )
3. Try running the script in the repl. (`ctrl+,, f`)
4. Close the repl tab (`ctrl+w`)
5. Open another repl.
6. Try running the script again.

Traceback:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 231, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 270, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "C:\Users\a\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 748, in on_close
    rv.on_close()
  File "C:\Users\a\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 262, in on_close
    self.repl.close()
  File "C:\Users\a\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repls\repl.py", line 59, in close
    if self.is_alive():
  File "C:\Users\a\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repls\subprocess_repl.py", line 209, in is_alive
    return self.popen.poll() is None
  File "./subprocess.py", line 938, in poll
  File "./subprocess.py", line 1153, in _internal_poll
OSError: [WinError 6] The handle is invalid
```
mFingers's trick, finding the dead process and killing it, works for me.

**Comment by Boscop** [comment]
I'm on Win 10 with TidalCycles (ghci, Haskell), I followed the instructions here:
https://tidalcycles.org/docs/getting-started/editor/Sublime_Text/#configuration-for-tidal

When I do `Ctrl+Shift+P -> “Sublime REPL: Tidal”`, it opens a new tab with ghci as expected, but evaluating code (with one of the key combos, e.g. `{ "keys": ["ctrl+,", "l"], "command": "repl_transfer_current", "args": {"scope": "lines"}}`) doesn't work, I get this error:
```python
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
  File "C:\Users\me\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\text_transfer.py", line 141, in run
    for rv in manager.find_repl(external_id):
  File "C:\Users\me\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 470, in find_repl
    if not (rv.repl and rv.repl.is_alive()):
  File "C:\Users\me\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repls\subprocess_repl.py", line 209, in is_alive
    return self.popen.poll() is None
  File "./python3.3/subprocess.py", line 930, in poll
  File "./python3.3/subprocess.py", line 1145, in _internal_poll
OSError: [WinError 6] The handle is invalid
```

Any idea how to make it work? :)

---

Edit: I restarted Sublime, now when I try to evaluate code, I get this error:
> error: Cannot find REPL for 'plain'

And every time I do `Ctrl+Shift+P -> “Sublime REPL: Tidal”`, it just opens another ghci tab:

![image](https://user-images.githubusercontent.com/535593/126048227-728e24db-5a25-4182-be4b-0c4b70b09840.png)

My `test.tidal` file is opened in plain text mode. There is no Tidal entry here:

![image](https://user-images.githubusercontent.com/535593/126048274-4a0b2d09-1bcf-494f-a969-21f745f4690c.png)
