### ISSUE TITLE
Attempting to get functioning Execnet virtualenv REPL

### ISSUE THREAD

**Issue by phunter** [wuub/SublimeREPL#346]
I've been attempting to use the execnet REPL as seen in your impressive youtube video: http://www.youtube.com/watch?v=zodAqBvKQm0

First of all my I'm using Sublime Text 2 Version 2.0.2, Build 2221. I've made it as far as inputing the ssh host and getting back a dropdown of the remote virtualenvs (and one option for 'w/o venv'). However, no matter which of these I choose I get back an alert saying "NoReplError()". The traceback in my Sublime console gives the following info:

```
Traceback (most recent call last):
  File "./sublimerepl.py", line 454, in open
  File "./repls/repl.py", line 27, in subclass
NoReplError
error: NoReplError()
```

I've looked at the relevant lines of code, but I'm afraid I'm a bit lost as to what the problem could be. Any ideas? Thanks.

As a side note, I gather based on your note in messages/2.0.0.txt:

```
REMOVED: Execnet REPL (for now, waiting for community input, anyone uses this?)
```

that this is all rather under-tested and under-used. Is the functionality even sill there?

**Comment by tronghieu1987** [comment]
Hello @wuub  and @phunter, I am trying to set up SublimeREPL to work with a remote ssh, but having a hard time understand what @wuub said above about proxychains4 and neehi. Could you please give more detailed procedure? Or if there is a different way to accomplish this, it would be even better.

Thank you!
