### ISSUE TITLE
'ZMQSocketChannel' object has no attribute 'complete'

### ISSUE THREAD

**Issue by LxMit** [wuub/SublimeREPL#407]
I use anaconda python in windows 8.1, and I get this error.
```
IPython Console 3.0.0

In [1]: Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Sublime Text 3\Data\Packages/SublimeREPL/config/Python/ipy_repl.py", line 104, in handle
    completions = complete(embedded_shell, req)
  File "D:\Sublime Text 3\Data\Packages/SublimeREPL/config/Python/ipy_repl.py", line 92, in complete
    msg_id = kc.shell_channel.complete(**req)
AttributeError: 'ZMQSocketChannel' object has no attribute 'complete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Sublime Text 3\Data\Packages/SublimeREPL/config/Python/ipy_repl.py", line 109, in handle
    send_netstring(s, b"[]")
  File "D:\Sublime Text 3\Data\Packages/SublimeREPL/config/Python/ipy_repl.py", line 86, in send_netstring
    payload = b"".join([str(len(msg)).encode("ascii"), b':', msg.encode("utf-8"), b','])
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by j9ac9k** [comment]
This is the same issue as #417
