### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by littlee** [wuub/SublimeREPL#422]
I open a simple .js file.
and installed sublimeREPL
and installed Node.js
and press ctrl + B;

but I get this error:
```
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl_build_system_hack.py", line 16, in run
    RESULTS.put(cmd)
AttributeError: 'NoneType' object has no attribute 'put'
```

**Comment by duqcyxwd** [comment]
Tools -> Build System, then select right one.
