### ISSUE TITLE
Bad File Descriptor When Connecting to Clojure-Telnet REPL

### ISSUE THREAD

**Issue by damienstanton** [wuub/SublimeREPL#424]
Connecting to local REPL works fine, but when connecting via `lein repl :headless` the following is returned:

```python
Unable to open /Users/dstanton/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap
no command for selector: noop:
no command for selector: noop:
Exception in thread Thread-11:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl.py", line 71, in run
    result = r.read()
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repls/repl.py", line 91, in read
    bs = self.read_bytes()
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repls/telnet_repl.py", line 35, in read_bytes
    return self._telnet.read_some()
  File "./telnetlib.py", line 399, in read_some
  File "./telnetlib.py", line 575, in fill_rawq
OSError: [Errno 9] Bad file descriptor

Exception in thread Thread-13:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl.py", line 71, in run
    result = r.read()
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repls/repl.py", line 91, in read
    bs = self.read_bytes()
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repls/telnet_repl.py", line 35, in read_bytes
    return self._telnet.read_some()
  File "./telnetlib.py", line 399, in read_some
  File "./telnetlib.py", line 575, in fill_rawq
OSError: [Errno 9] Bad file descriptor

Exception in thread Thread-15:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl.py", line 71, in run
    result = r.read()
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repls/repl.py", line 91, in read
    bs = self.read_bytes()
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repls/telnet_repl.py", line 35, in read_bytes
    return self._telnet.read_some()
  File "./telnetlib.py", line 399, in read_some
  File "./telnetlib.py", line 575, in fill_rawq
OSError: [Errno 9] Bad file descriptor

no command for selector: noop:
```

The REPL tab just hangs and must be closed.

Versions:
`OS X 10.10.3`
`Sublime Text 3, Stable Channel Build 3083`
`Leiningen 2.5.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM`
`REPL-y 0.3.5, nREPL 0.2.6`
`Clojure 1.6.0`
`Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-b25`

**Comment by damienstanton** [comment]
After a reboot the `nrepl` session still hangs, but the ST console is empty. Closing until this issue can be accurately reproduced with a traceback.
