### ISSUE TITLE
Eval in Gambit Scheme doesn't work

### ISSUE THREAD

**Issue by vidjuheffex** [wuub/SublimeREPL#426]
I've got the REpl working, however if I check the console after trying to eval or transfer I get:

ValueError: zero length field name in format
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
  File ".\text_transfer.py", line 132, in run
ValueError: zero length field name in format

If I check \text_trasfer.py at that line I find that it's an error-msg line for not finding the Repl, im not getting this error, im getting a bug at the point at which it would flag this error. (which doesn't make sense since the REpl is functioning fine)

**Comment by wickedjargon** [comment]
I get the same error:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./text_transfer.py", line 132, in run
ValueError: zero length field name in format

however, mine is for petite-chez-scheme. Can anyone help me out?
