### ISSUE TITLE
Multiple REPLs getting FileNotFoundError, even if explicitly in both PATH and default_extend_path

### ISSUE THREAD

**Issue by damienstanton** [wuub/SublimeREPL#438]
I have tested this on two different OS X machines running 10.10.5 and Groovy Shell 2.4.4, Java 1.8. and various versions of Haskell, Ruby and Node.

I'll use Groovy to illustrate as that was where I found this problem.

```
FileNotFoundError(2, "No such file or directory: 'groovysh'")
```

In my terminal `which groovysh` returns:

```
/Users/dstanton/.gvm/groovy/current/bin
```

I added this to my `PATH`, and when that did not work I added it to the `default_extend_env` key in Sublime config. I am still getting the same error.

Sublime log shows the following:

```
Traceback (most recent call last):
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl.py", line 454, in open
    r = repls.Repl.subclass(type)(encoding, **kwds)
  File "/Users/dstanton/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repls/subprocess_repl.py", line 92, in __init__
    stdout=subprocess.PIPE)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'groovysh'
error: FileNotFoundError(2, "No such file or directory: 'groovysh'")
```

I have also tried this with Haskell (same result) Node (crashes immediately) and Ruby (crashes immediately). Bash in SublimeREPL also has several issues and cannot find anything in `PATH`.

Python, Scala and Clojure seem to be the only REPLs working at this time.

**Comment by damienstanton** [comment]
A fresh install of ST3 and modification of the subprocess REPL configs for relevant languages resolved it for me.
