### ISSUE TITLE
Eval in REPL "[Errno 22] Invalid argument"

### ISSUE THREAD

**Issue by jiroler** [wuub/SublimeREPL#486]
`Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "C:\Users\test\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\text_transfer.py", line 147, in run
    SENDERS[external_id](rv.repl, text, self.view, rv)
  File "C:\Users\test\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\text_transfer.py", line 68, in python_sender
    return default_sender(repl, execute, view, repl_view)
  File "C:\Users\test\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\text_transfer.py", line 20, in default_sender
    repl.write(text)
  File "C:\Users\test\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repls\repl.py", line 85, in write
    return self.write_bytes(bytes)
  File "C:\Users\test\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repls\subprocess_repl.py", line 235, in write_bytes
    si.flush()
OSError: [Errno 22] Invalid argument`

I am beginner in using ST3 and Python. I try run simple py-code:

`print(1)`

and got error.

Windows 7, python3

**Comment by luzhnyak** [comment]
Same problem (OSError: [Errno 22] Invalid argument) on Windows 10 64bit with Sublime 3 and Python 3.4 installed, when I run "Eval in REPL -> File".

**Comment by lzkhahahh** [comment]
It's the same with me, and there's nothing in the repl interface
![image](https://user-images.githubusercontent.com/30492708/107107771-37fdc000-686e-11eb-81b6-7bc3bee37c18.png)
