### ISSUE TITLE
When trying to start a Node REPL I get an error

### ISSUE THREAD

**Issue by playeren** [wuub/SublimeREPL#500]
Win 8.1, ST3 3126

```
readline.js:245
    throw new TypeError('"stringToWrite" argument must be a string');
    ^

TypeError: "stringToWrite" argument must be a string
    at REPLServer._writeToOutput (readline.js:245:11)
    at REPLServer.Interface.prompt (readline.js:213:10)
    at REPLServer.displayPrompt (repl.js:753:8)
    at new REPLServer (repl.js:640:8)
    at Object.exports.start (repl.js:657:14)
    at C:\Users\USER\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:5:20
    at Object.<anonymous> (C:\Users\USER\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\config\NodeJS\repl.js:38:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

***Repl Closed***
```

Any ideas?

**Comment by playeren** [comment]
Found solution here https://github.com/wuub/SublimeREPL/issues/364
