### ISSUE TITLE
REPL: R UnicodeDecodeError

### ISSUE THREAD

**Issue by blizzardwj** [wuub/SublimeREPL#554]
Win10, R3.5.0, sublime text 3+R-box+sendcode 
"default_extend_env": {"PATH": "{PATH};C:\\Program Files\\R\\R-3.5.0\\bin\\x64"},

```
Traceback (most recent call last):
  File "C:\Users\admin_wj\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 487, in open
    r = repls.Repl.subclass(type)(encoding, **kwds)
File "C:\Users\admin_wj\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repls\subprocess_repl.py", line 77, in __init__
    strings_env[k.decode("utf-8")] = v.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 0: invalid continuation byte
error: UnicodeDecodeError('utf-8', b'\xd6\xdc\xcb\xc4 6\xd4\xc2 29 15:15:02 2017', 0, 1, 'invalid continuation byte')
```
I'm not sure about what file should be read when I execute REPL: R.

But after I have changed the following lines in "Packages\SublimeREPL\repls\subprocess_repl.py"
```
# strings_env[k.decode("utf-8")] = v.decode("utf-8")
strings_env[k.decode("utf-8")] = v.decode("latin-1")
```
 the error went away.

In my laptop, the same enviroment, it works well. No need to change "utf-8" to "latin-1" .

I want to know where actually the byte "0xd6" is.

**Comment by lidingruc** [comment]
when i  use REPL: R, the path cannot have Chinese characters and space,otherwise they will be changed to mass code and all chinese characters showed in the console become some encoding numbers.
what i want to do is:
setwd("~/E/研究/组织与治理/data/")
list.files()

but the output in the console is, it only list the file in folder "~/E/"

> setwd("~/E/
(arg: 6) setwd("~/E/
> setwd("~/E/      //////
(arg: 8) setwd("~/E///////
> setwd("~/E///////      
(arg: 2) setwd("~/E///////
> setwd("~/E///////      /data/")
Error in setwd("~/E////////data/") : cannot change working directory
> list.files()
[1] "Bdata"                                                           
[2] "U\347\233\230"                                                   
[3] "learning"                                                        
[4] "\344\272\272\344\272\272\347\275\221\347\210\254\350\231\253.txt"
[5] "\345\267\245\344\275\234"                                        
[6] "\346\226\207\347\214\256"                                        
[7] "\347\224\237\346\264\273"                                        
[8] "\347\240\224\347\251\266"                                        
[9] "\350\264\242\345\212\241"
<img width="375" alt="image" src="https://user-images.githubusercontent.com/16370784/52158155-628d6f00-26d0-11e9-98eb-77787d18bab9.png">

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] C
