### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'put'

### ISSUE THREAD

**Issue by ghost** [wuub/SublimeREPL#564]
```
tail -f ~/.subl.log
=> => => [18 Dec 2018, 22:16:40] Console logging activated (/home/nicholas/.subl.log).
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1034, in run_
    return self.run(**args)
  File "/home/<username>/.config/sublime-text-3/Packages/SublimeREPL/sublimerepl_build_system_hack.py", line 16, in run
    RESULTS.put(cmd)
AttributeError: 'NoneType' object has no attribute 'put'
```
Linux Mint 19.0 Cinnamon. Sublime Text build 3184.

And - perhaps related, perhaps not - when editing large text files, I get stutters and hangs (as described in [this bug report](https://github.com/SublimeTextIssues/Core/issues/2523)). Perhaps cf. #226, #450.

**Comment by hsandt** [comment]
Just started getting this on Sublime Text 4107. To repro, open a file without build commands like the sublime-keymap, then try to open the build command popup (I use Ctrl+Shift+B). Adding `if cmd:` to check for None seems to silence the error message, but also prevents opening the build popup even on valid files altogether...

EDIT: Removing this package for now, I seem unable to use the build command panel on projects with custom build commands otherwise.
