### ISSUE TITLE
UnpicklingError("invalid load key, '\x03'.",)

### ISSUE THREAD

**Issue by epszaw** [wuub/SublimeREPL#578]
**Sublime text 3**: 3.2.1 3207
**OS**: OSX 10.14.6

Hello! Having problem with text from title when trying to launch Clojure repl.

**Comment by ipstone** [comment]
I have the same error msg when launching sublmeREPL for R /python

**Comment by ipstone** [comment]
Some more details on the error: 

```
error: UnpicklingError("invalid load key, '\x03'.",)
Traceback (most recent call last):
  File "/Users/peix/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl.py", line 495, in open
    rv = ReplView(view, r, syntax, repl_restart_args)
  File "/Users/peix/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl.py", line 186, in __init__
    self._history = PersistentHistory(self.external_id)
  File "/Users/peix/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/sublimerepl.py", line 140, in __init__
    self._db.create("external_id", "command", "ts", mode="open")
  File "/Users/peix/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repllibs/PyDbLite.py", line 193, in create
    return self.open()
  File "/Users/peix/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/repllibs/PyDbLite.py", line 246, in open
    self.fields = pickle.load(_in)
_pickle.UnpicklingError: invalid load key, ''.
error: UnpicklingError("invalid load key, '\x03'.",)
top level value must be an array```

**Comment by ipstone** [comment]
Found the solution: #251 

Just pasted the answer quickly here: 

> "SublimeREPL's history file got corrupted during crash.
> 
> Remove config/sublime-text-3/Packages/User/.SublimeREPLHistory/r.db and everything should be back to normal."
>

**Comment by ipstone** [comment]
For mac os x, the file is located at /Users/your_user_name/Library/Application Support/Sublime Text 3/Packages/User/.SublimeREPLHistory
